# Generated by Django 5.1.3 on 2024-11-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_actor_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='surname',
        ),
    ]
