version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-netflix
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onamotam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  postgres_data:
