name: Movie API CI

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: netflix
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: onamotam
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: pdp-django.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
